export const FIAT_CURRENCIES: Record<string, { symbol: string, name: string, aliases?: string[] }> = {
  // 主要发达国家
  'usd': { symbol: 'USD', name: 'US Dollar' },
  'eur': { symbol: 'EUR', name: 'Euro' },
  'gbp': { symbol: 'GBP', name: 'British Pound' },
  'jpy': { symbol: 'JPY', name: 'Japanese Yen' },
  'cny': { symbol: 'CNY', name: 'Chinese Yuan', aliases: ['rmb', 'yuan', 'cnh'] },
  'cad': { symbol: 'CAD', name: 'Canadian Dollar' },
  'aud': { symbol: 'AUD', name: 'Australian Dollar' },
  'chf': { symbol: 'CHF', name: 'Swiss Franc' },
  'nzd': { symbol: 'NZD', name: 'New Zealand Dollar' },

  // 北欧国家
  'sek': { symbol: 'SEK', name: 'Swedish Krona' },
  'nok': { symbol: 'NOK', name: 'Norwegian Krone' },
  'dkk': { symbol: 'DKK', name: 'Danish Krone' },
  'isk': { symbol: 'ISK', name: 'Icelandic Krona' },

  // 东欧国家
  'pln': { symbol: 'PLN', name: 'Polish Zloty' },
  'czk': { symbol: 'CZK', name: 'Czech Koruna' },
  'huf': { symbol: 'HUF', name: 'Hungarian Forint' },
  'ron': { symbol: 'RON', name: 'Romanian Leu' },
  'bgn': { symbol: 'BGN', name: 'Bulgarian Lev' },
  'hrk': { symbol: 'HRK', name: 'Croatian Kuna' },
  'rsd': { symbol: 'RSD', name: 'Serbian Dinar' },
  'bam': { symbol: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
  'mkd': { symbol: 'MKD', name: 'Macedonian Denar' },
  'all': { symbol: 'ALL', name: 'Albanian Lek' },
  'rub': { symbol: 'RUB', name: 'Russian Ruble' },
  'uah': { symbol: 'UAH', name: 'Ukrainian Hryvnia' },
  'byn': { symbol: 'BYN', name: 'Belarusian Ruble' },
  'mdl': { symbol: 'MDL', name: 'Moldovan Leu' },

  // 土耳其和高加索
  'try': { symbol: 'TRY', name: 'Turkish Lira' },
  'gel': { symbol: 'GEL', name: 'Georgian Lari' },
  'amd': { symbol: 'AMD', name: 'Armenian Dram' },
  'azn': { symbol: 'AZN', name: 'Azerbaijani Manat' },

  // 美洲
  'brl': { symbol: 'BRL', name: 'Brazilian Real' },
  'mxn': { symbol: 'MXN', name: 'Mexican Peso' },
  'ars': { symbol: 'ARS', name: 'Argentine Peso' },
  'cop': { symbol: 'COP', name: 'Colombian Peso' },
  'pen': { symbol: 'PEN', name: 'Peruvian Sol' },
  'clp': { symbol: 'CLP', name: 'Chilean Peso' },
  'uyu': { symbol: 'UYU', name: 'Uruguayan Peso' },
  'pyg': { symbol: 'PYG', name: 'Paraguayan Guarani' },
  'bob': { symbol: 'BOB', name: 'Bolivian Boliviano' },
  'ves': { symbol: 'VES', name: 'Venezuelan Bolívar' },
  'gyd': { symbol: 'GYD', name: 'Guyanese Dollar' },
  'srd': { symbol: 'SRD', name: 'Surinamese Dollar' },
  'ttd': { symbol: 'TTD', name: 'Trinidad and Tobago Dollar' },
  'jmd': { symbol: 'JMD', name: 'Jamaican Dollar' },
  'bbd': { symbol: 'BBD', name: 'Barbadian Dollar' },
  'bsd': { symbol: 'BSD', name: 'Bahamian Dollar' },
  'bzd': { symbol: 'BZD', name: 'Belize Dollar' },
  'crc': { symbol: 'CRC', name: 'Costa Rican Colón' },
  'gtq': { symbol: 'GTQ', name: 'Guatemalan Quetzal' },
  'hnl': { symbol: 'HNL', name: 'Honduran Lempira' },
  'nio': { symbol: 'NIO', name: 'Nicaraguan Córdoba' },
  'pab': { symbol: 'PAB', name: 'Panamanian Balboa' },
  'dop': { symbol: 'DOP', name: 'Dominican Peso' },
  'htg': { symbol: 'HTG', name: 'Haitian Gourde' },
  'cub': { symbol: 'CUP', name: 'Cuban Peso' },

  // 亚太地区
  'sgd': { symbol: 'SGD', name: 'Singapore Dollar' },
  'hkd': { symbol: 'HKD', name: 'Hong Kong Dollar' },
  'krw': { symbol: 'KRW', name: 'South Korean Won' },
  'inr': { symbol: 'INR', name: 'Indian Rupee' },
  'thb': { symbol: 'THB', name: 'Thai Baht' },
  'myr': { symbol: 'MYR', name: 'Malaysian Ringgit' },
  'php': { symbol: 'PHP', name: 'Philippine Peso' },
  'idr': { symbol: 'IDR', name: 'Indonesian Rupiah' },
  'vnd': { symbol: 'VND', name: 'Vietnamese Dong' },
  'lak': { symbol: 'LAK', name: 'Lao Kip' },
  'khr': { symbol: 'KHR', name: 'Cambodian Riel' },
  'mmk': { symbol: 'MMK', name: 'Myanmar Kyat' },
  'bnd': { symbol: 'BND', name: 'Brunei Dollar' },
  'twd': { symbol: 'TWD', name: 'Taiwan Dollar' },
  'mop': { symbol: 'MOP', name: 'Macanese Pataca' },
  'fjd': { symbol: 'FJD', name: 'Fijian Dollar' },
  'pgk': { symbol: 'PGK', name: 'Papua New Guinea Kina' },
  'sbd': { symbol: 'SBD', name: 'Solomon Islands Dollar' },
  'vuv': { symbol: 'VUV', name: 'Vanuatu Vatu' },
  'top': { symbol: 'TOP', name: 'Tongan Paʻanga' },
  'wst': { symbol: 'WST', name: 'Samoan Tala' },

  // 南亚
  'lkr': { symbol: 'LKR', name: 'Sri Lankan Rupee' },
  'pkr': { symbol: 'PKR', name: 'Pakistani Rupee' },
  'bdt': { symbol: 'BDT', name: 'Bangladeshi Taka' },
  'npr': { symbol: 'NPR', name: 'Nepalese Rupee' },
  'btn': { symbol: 'BTN', name: 'Bhutanese Ngultrum' },
  'mvr': { symbol: 'MVR', name: 'Maldivian Rufiyaa' },
  'afn': { symbol: 'AFN', name: 'Afghan Afghani' },

  // 中亚
  'kzt': { symbol: 'KZT', name: 'Kazakhstani Tenge' },
  'uzs': { symbol: 'UZS', name: 'Uzbekistani Som' },
  'kgs': { symbol: 'KGS', name: 'Kyrgyzstani Som' },
  'tjs': { symbol: 'TJS', name: 'Tajikistani Somoni' },
  'tmm': { symbol: 'TMT', name: 'Turkmenistani Manat' },

  // 中东
  'zar': { symbol: 'ZAR', name: 'South African Rand' },
  'ils': { symbol: 'ILS', name: 'Israeli Shekel' },
  'aed': { symbol: 'AED', name: 'UAE Dirham' },
  'sar': { symbol: 'SAR', name: 'Saudi Riyal' },
  'qar': { symbol: 'QAR', name: 'Qatari Riyal' },
  'kwd': { symbol: 'KWD', name: 'Kuwaiti Dinar' },
  'bhd': { symbol: 'BHD', name: 'Bahraini Dinar' },
  'omr': { symbol: 'OMR', name: 'Omani Rial' },
  'jod': { symbol: 'JOD', name: 'Jordanian Dinar' },
  'lbp': { symbol: 'LBP', name: 'Lebanese Pound' },
  'syp': { symbol: 'SYP', name: 'Syrian Pound' },
  'iqd': { symbol: 'IQD', name: 'Iraqi Dinar' },
  'irr': { symbol: 'IRR', name: 'Iranian Rial' },
  'yer': { symbol: 'YER', name: 'Yemeni Rial' },

  // 非洲北部
  'egp': { symbol: 'EGP', name: 'Egyptian Pound' },
  'mad': { symbol: 'MAD', name: 'Moroccan Dirham' },
  'dzd': { symbol: 'DZD', name: 'Algerian Dinar' },
  'tnd': { symbol: 'TND', name: 'Tunisian Dinar' },
  'lyd': { symbol: 'LYD', name: 'Libyan Dinar' },
  'sdg': { symbol: 'SDG', name: 'Sudanese Pound' },
  'etb': { symbol: 'ETB', name: 'Ethiopian Birr' },
  'ern': { symbol: 'ERN', name: 'Eritrean Nakfa' },
  'djf': { symbol: 'DJF', name: 'Djiboutian Franc' },
  'sos': { symbol: 'SOS', name: 'Somali Shilling' },

  // 非洲西部
  'ngn': { symbol: 'NGN', name: 'Nigerian Naira' },
  'ghs': { symbol: 'GHS', name: 'Ghanaian Cedi' },
  'xof': { symbol: 'XOF', name: 'West African CFA Franc' },
  'sll': { symbol: 'SLL', name: 'Sierra Leonean Leone' },
  'lrd': { symbol: 'LRD', name: 'Liberian Dollar' },
  'gmd': { symbol: 'GMD', name: 'Gambian Dalasi' },
  'gnf': { symbol: 'GNF', name: 'Guinean Franc' },
  'cvs': { symbol: 'CVE', name: 'Cape Verdean Escudo' },

  // 非洲东部
  'kes': { symbol: 'KES', name: 'Kenyan Shilling' },
  'ugx': { symbol: 'UGX', name: 'Ugandan Shilling' },
  'tzs': { symbol: 'TZS', name: 'Tanzanian Shilling' },
  'rwf': { symbol: 'RWF', name: 'Rwandan Franc' },
  'bif': { symbol: 'BIF', name: 'Burundian Franc' },
  'mzn': { symbol: 'MZN', name: 'Mozambican Metical' },
  'mwk': { symbol: 'MWK', name: 'Malawian Kwacha' },
  'zmw': { symbol: 'ZMW', name: 'Zambian Kwacha' },
  'zwd': { symbol: 'ZWL', name: 'Zimbabwean Dollar' },
  'mga': { symbol: 'MGA', name: 'Malagasy Ariary' },
  'mur': { symbol: 'MUR', name: 'Mauritian Rupee' },
  'scr': { symbol: 'SCR', name: 'Seychellois Rupee' },
  'kmf': { symbol: 'KMF', name: 'Comorian Franc' },

  // 非洲中部
  'xaf': { symbol: 'XAF', name: 'Central African CFA Franc' },
  'cdf': { symbol: 'CDF', name: 'Congolese Franc' },
  'aoa': { symbol: 'AOA', name: 'Angolan Kwanza' },
  'std': { symbol: 'STN', name: 'São Tomé and Príncipe Dobra' },
  'gqe': { symbol: 'XAF', name: 'Equatorial Guinea CFA Franc' },

  // 非洲南部
  'bwp': { symbol: 'BWP', name: 'Botswana Pula' },
  'nad': { symbol: 'NAD', name: 'Namibian Dollar' },
  'szl': { symbol: 'SZL', name: 'Swazi Lilangeni' },
  'lsl': { symbol: 'LSL', name: 'Lesotho Loti' }
};

// 内置加密货币映射表 - 前30名主流加密货币
export const CRYPTO_CURRENCIES: Record<string, { symbol: string, name: string, aliases?: string[] }> = {
  'btc': { symbol: 'BTC', name: 'Bitcoin', aliases: ['bitcoin'] },
  'eth': { symbol: 'ETH', name: 'Ethereum', aliases: ['ethereum'] },
  'usdt': { symbol: 'USDT', name: 'Tether', aliases: ['tether'] },
  'bnb': { symbol: 'BNB', name: 'BNB', aliases: ['binancecoin'] },
  'sol': { symbol: 'SOL', name: 'Solana', aliases: ['solana'] },
  'usdc': { symbol: 'USDC', name: 'USD Coin', aliases: ['usd-coin'] },
  'xrp': { symbol: 'XRP', name: 'XRP', aliases: ['ripple'] },
  'doge': { symbol: 'DOGE', name: 'Dogecoin', aliases: ['dogecoin'] },
  'ton': { symbol: 'TON', name: 'Toncoin', aliases: ['toncoin'] },
  'ada': { symbol: 'ADA', name: 'Cardano', aliases: ['cardano'] },
  'shib': { symbol: 'SHIB', name: 'Shiba Inu', aliases: ['shiba-inu'] },
  'avax': { symbol: 'AVAX', name: 'Avalanche', aliases: ['avalanche-2'] },
  'trx': { symbol: 'TRX', name: 'TRON', aliases: ['tron'] },
  'dot': { symbol: 'DOT', name: 'Polkadot', aliases: ['polkadot'] },
  'link': { symbol: 'LINK', name: 'Chainlink', aliases: ['chainlink'] },
  'matic': { symbol: 'MATIC', name: 'Polygon', aliases: ['matic-network'] },
  'wbtc': { symbol: 'WBTC', name: 'Wrapped Bitcoin', aliases: ['wrapped-bitcoin'] },
  'ltc': { symbol: 'LTC', name: 'Litecoin', aliases: ['litecoin'] },
  'bch': { symbol: 'BCH', name: 'Bitcoin Cash', aliases: ['bitcoin-cash'] },
  'uni': { symbol: 'UNI', name: 'Uniswap', aliases: ['uniswap'] },
  'atom': { symbol: 'ATOM', name: 'Cosmos', aliases: ['cosmos'] },
  'etc': { symbol: 'ETC', name: 'Ethereum Classic', aliases: ['ethereum-classic'] },
  'xlm': { symbol: 'XLM', name: 'Stellar', aliases: ['stellar'] },
  'okb': { symbol: 'OKB', name: 'OKB' },
  'icp': { symbol: 'ICP', name: 'Internet Computer', aliases: ['internet-computer'] },
  'fil': { symbol: 'FIL', name: 'Filecoin', aliases: ['filecoin'] },
  'hbar': { symbol: 'HBAR', name: 'Hedera', aliases: ['hedera-hashgraph'] },
  'ldo': { symbol: 'LDO', name: 'Lido DAO', aliases: ['lido-dao'] },
  'crv': { symbol: 'CRV', name: 'Curve DAO Token', aliases: ['curve-dao-token'] },
  'arb': { symbol: 'ARB', name: 'Arbitrum', aliases: ['arbitrum'] }
};
